# Fix problems with bad names that I picked earlier for exparray.

# s/CREATE_EXP_ARRAY_TYPE/ARRAY_CREATE_TYPE/g
# s/INIT_ARRAY/ARRAY_INIT/g
# s/DESTROY_ARRAY/ARRAY_DESTROY/g
s/GROW_ARRAY_REALLOC/ARRAY_GROW/g
s/ADD_ARRAY_ELMT/ARRAY_ADD/g
s/INSERT_ARRAY_ELMT/ARRAY_INSERT/g
s/DELETE_ARRAY_ELMT/ARRAY_DELETE/g
# s/NORMALIZE_ARRAY/ARRAY_NORMALIZE/g
